import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const font = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='light'>
      <body className={`${font.variable} antialiased light`}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  )
}
